# Streamlit Secrets Template
# IKKE commit denne filen med ekte verdier!
# Denne brukes som template for Streamlit Cloud deployment

[supabase]
url = "https://your-project-id.supabase.co"
anon_key = "your-anon-key-here"

[app]
name = "Konkurranseapp"
version = "1.0.0"
debug_mode = false
secret_key = "your-secret-key-here"
